Repository PriyaGhosal/SkillWise, pull requests merged in 2024-10, with the labels that each got.

#6 Corrected Spelling of word Terms
  index.html
Labels: hacktoberfest-accepted

#50 The footer links to the different components of the page are working now
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#85 Navigation Bar is fixed now
  assets/css/style.css
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#86 [Fix #25] - Navbar Link Issue: Section Navigation
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#91 Add a Separate Copyright Policy Page
  copy.html
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#89 Issue #12 solved , Footer is responsive now !
  assets/css/style.css
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#7 #4 Landing Page : Removed one extra button
  index.html
Labels: enhancement, hacktoberfest

#41 Add blank blog, contacts, and courses pages with consistent navbar
  index.html
  pages/blog.html
  pages/contact.html
  pages/courses.html
Labels: hacktoberfest, hacktoberfest-accepted

#74 Added FAQ Section
  Faq.html
  assets/css/Faq.css
  assets/images/faq.png
  assets/js/scriptfaq.js
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#92 created a signin page #84
  assets/css/signin.css
  assets/images/finance-icon.jpeg
  assets/images/marketing.jpeg
  index.html
  signin.html
Labels: hacktoberfest, hacktoberfest-accepted

#96 Accessibility and SEO Improvements for data-science.html
  data-science.html
Labels: hacktoberfest, hacktoberfest-accepted

#464 Update package-lock.json
  package-lock.json
Labels: hacktoberfest, hacktoberfest-accepted

#602 Improved register section UI on both light and dark mode #544
  assets/css/darkmode.css
  assets/css/style.css
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#474 perf courses.html
  pages/courses.html
Labels: hacktoberfest, hacktoberfest-accepted

#600 corrected the nav bar also in dark mode
  assets/css/darkmode.css
  index.html
  style.css
Labels: hacktoberfest, hacktoberfest-accepted

#612 fix: navbar non functionality and alignment in career page
  Faq.html
  assets/css/career.css
  careers.html
Labels: hacktoberfest, hacktoberfest-accepted

#628 Update Email Validator
  Email Validator
Labels: hacktoberfest, hacktoberfest-accepted

#631 Fix : email validation function
  signin.html
Labels: hacktoberfest, hacktoberfest-accepted

#636 Updated SearchMain.py
  SearchMain.py
  marketing.html
Labels: hacktoberfest, hacktoberfest-accepted

#691 Update README.md - Fixing hyperlink for Sign up page
  README.md
Labels: hacktoberfest, hacktoberfest-accepted

#682 Improved Register section UI on home page
  index.html
  style.css
Labels: hacktoberfest, hacktoberfest-accepted

#688 i have added youtube image and hover effect
  assets/images/youtube.svg
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#668 modify Copyright.html
  Copyright.html
Labels: hacktoberfest, hacktoberfest-accepted

#710 #564 Solved [BUG] : Email Validation in login page
  emailValidator.js
Labels: hacktoberfest-accepted

#713 #475 Solved -Resolves Hover Issues and HTML Errors for Course Cards (Headers 1-6)
  assets/css/style.css
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#718 Fixes #717 : searchbar now shows result when enter key is pressed
  index.html
Labels: hacktoberfest, hacktoberfest-accepted

#734 Update blog.js
  assets/js/blog.js
  signin.html
Labels: hacktoberfest-accepted

#789 feat: Adjusted button smoother UI experience
  index.html
  style.css
Labels: hacktoberfest-accepted

#818 Am edited the copyright in the footer section of dark theme
  assets/css/darkmode.css
Labels: hacktoberfest-accepted

#822 Changed the Subscribe color and Added a Button
  assets/css/style.css
  index.html
  signup.html
Labels: hacktoberfest, hacktoberfest-accepted

#839 Added UI to E-book page
  E-Book.html
Labels: hacktoberfest-accepted

#838 Enhanced contact us
  pages/blog.html
Labels: hacktoberfest-accepted

#842 Revert "Enhanced contact us"
  pages/blog.html
Labels: hacktoberfest-accepted

#833 Bug: changes in size of nav button to enhance UI of Opportunity page
  assets/css/career.css
  style.css
Labels: hacktoberfest-accepted

#827 New Feature: Cloud Storage Course Category added with its page #825
  Course.html
  assets/images/Cloud_Storage/Azure.jpg
  assets/images/Cloud_Storage/Cloud-icon.jpeg
  assets/images/Cloud_Storage/Dropbox.png
  assets/images/Cloud_Storage/aws.jpg
  assets/images/Cloud_Storage/google_cloud_storage.png
  cloud.html
  index.html
Labels: hacktoberfest-accepted
